//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERROR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERROR.Error_Resource", typeof(Error_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while flight searching.
        /// </summary>
        internal static string Error_001 {
            get {
                return ResourceManager.GetString("Error_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while flight proccessing.
        /// </summary>
        internal static string Error_002 {
            get {
                return ResourceManager.GetString("Error_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while flight booking.
        /// </summary>
        internal static string Error_003 {
            get {
                return ResourceManager.GetString("Error_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while flight ticketing.
        /// </summary>
        internal static string Error_004 {
            get {
                return ResourceManager.GetString("Error_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while mailing ticket.
        /// </summary>
        internal static string Error_005 {
            get {
                return ResourceManager.GetString("Error_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while flight quotation mailing.
        /// </summary>
        internal static string Error_006 {
            get {
                return ResourceManager.GetString("Error_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while BAR.
        /// </summary>
        internal static string Error_007 {
            get {
                return ResourceManager.GetString("Error_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Import.
        /// </summary>
        internal static string Error_008 {
            get {
                return ResourceManager.GetString("Error_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Refund.
        /// </summary>
        internal static string Error_009 {
            get {
                return ResourceManager.GetString("Error_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Reissue.
        /// </summary>
        internal static string Error_010 {
            get {
                return ResourceManager.GetString("Error_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Report.
        /// </summary>
        internal static string Error_011 {
            get {
                return ResourceManager.GetString("Error_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while PAR.
        /// </summary>
        internal static string Error_012 {
            get {
                return ResourceManager.GetString("Error_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while finance settings.
        /// </summary>
        internal static string Error_013 {
            get {
                return ResourceManager.GetString("Error_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Settings.
        /// </summary>
        internal static string Error_014 {
            get {
                return ResourceManager.GetString("Error_014", resourceCulture);
            }
        }
    }
}
